### ISSUE TITLE
Running main

### ISSUE THREAD

**Issue by JokerMartini** [ideasman42/pyfbx_i42#2]
I'm not clear on how to run the main() with args? What are the expected args?

I tried this in the fbx2json.py file:

```
def main():
    import sys

    files = []
    files.append("C:/Users/jmartini/Projects/python_fbx_managing/assets/teapot_2012.FBX")

    for f in files:
        try:
            fbx2json(f)
        except:
            print("Failed to convert %r, error:" % f)

            import traceback
            traceback.print_exc()

if __name__ == "__main__":
    main()
```

However I get these errors:

> Writing: 'C:/Users/jmartini/Projects/python_fbx_managing/assets/teapot_2012.json' 
> (Version 7200) ...Traceback (most recent call last):
>   File "C:\Users\jmartini\Projects\python_fbx_managing\assets\pyfbx_i42-master\fbx2json.py", line 320, in main
> 
> Failed to convert 'C:/Users/jmartini/Projects/python_fbx_managing/assets/teapot_2012.FBX', error:
>     fbx2json(f)
>   File "C:\Users\jmartini\Projects\python_fbx_managing\assets\pyfbx_i42-master\fbx2json.py", line 299, in fbx2json
>     with open(fn_json, 'w', encoding="ascii", errors='xmlcharrefreplace') as f:
> TypeError: file() takes at most 3 arguments (4 given)
> [Finished in 0.1s]

**Comment by ideasman42** [comment]
This is written for Python3.x, updated readme.rst.
